<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestingSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4c766d0c-ab5e-4f81-84d7-9a7115d40b19</testSuiteGuid>
   <testCaseLink>
      <guid>0bfbccab-4d4b-45ef-8383-02bf16860b54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTestingExcel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>db2c0051-c0ba-401b-bf63-56716c83a996</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>db2c0051-c0ba-401b-bf63-56716c83a996</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>168a62f8-40a2-43ce-9f85-cba743a541d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>db2c0051-c0ba-401b-bf63-56716c83a996</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>02b365aa-8343-46d3-a798-e3e9c9ee1c41</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
